#!/usr/bin/env python

import sys
import rospy
from geometry_msgs.msg import Twist
from os.path import basename

import bot_actions as ba


def rotate(node_name, namespace="r0"):
    # Starts a new node
    rospy.init_node(node_name, anonymous=True)

    topic_name = '/%s/cmd_vel_mux/input/teleop' % (namespace,)
    vel_publisher = rospy.Publisher(topic_name, Twist, queue_size=10)
    rate = rospy.Rate(10)

    while not rospy.is_shutdown():
        vel_msg = ba.bot_actions['TnLeft']
        vel_publisher.publish(vel_msg)
        rate.sleep()


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print "usage: <script_name> <namespace>"
    else:
        try:
            #Testing our function
            rotate(basename(sys.argv[0]), sys.argv[1])
        except rospy.ROSInterruptException:
            pass
